#### Numpy Arrays
NumPy arrays are the core feature of NumPy, a powerful library for numerical computing in Python. These arrays are multidimensional array objects, also known as ndarray, which provide efficient storage and manipulation of large datasets, making them fundamental for scientific computing and various types of data analysis in Python. 

Homogeneous Data Type: NumPy arrays contain elements that are all of the same type, typically numeric (integers or floats), but also others like strings or objects. This homogeneity allows for efficient operations and storage.

Multidimensional: Arrays can have multiple dimensions, making it possible to represent data structures like vectors (1D arrays), matrices (2D arrays), and tensors (3D or higher-dimensional arrays) naturally within NumPy.

Slicing and Indexing: Advanced slicing and indexing features make it easy to select and manipulate specific elements, rows, columns, or sub-arrays within a larger array.

Efficient Memory Usage: NumPy arrays have a fixed size at creation, unlike Python lists which can grow dynamically. The fixed size and homogeneity of data types lead to more efficient memory usage.

NumPy arrays are a foundational tool for scientific computing in Python, underpinning many higher-level scientific and data analysis libraries like SciPy, Pandas, Matplotlib, and scikit-learn, enabling them to operate efficiently on large datasets.


In [1]:
import numpy as np

In [87]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [89]:
x = np.array([40,67,57,90])
print(x), print(type(x))

[40 67 57 90]
<class 'numpy.ndarray'>


(None, None)

#### 1D arrays

In [92]:
a = np.array([10,20,30,40])
a

array([10, 20, 30, 40])

In [93]:
a.shape, a.size

((4,), 4)

In [95]:
b = a.reshape(2,2)
b

array([[10, 20],
       [30, 40]])

In [96]:
b.ndim, b.shape,b.size

(2, (2, 2), 4)

In [8]:
b = np.array([1,2,3,4])
b

array([1, 2, 3, 4])

In [15]:
b.reshape(4)

array([10, 20, 30, 40])

In [14]:
type(a)

numpy.ndarray

In [97]:
c = np.arange(3,20,3)
c

array([ 3,  6,  9, 12, 15, 18])

In [38]:
print(c.ndim)
type(c)

1


numpy.ndarray

In [40]:
d = np.array([1.3467, 3.10987,4.91236])
np.around(d,2)

array([1.35, 3.11, 4.91])

In [19]:
d

array([1.3467 , 3.10987, 4.91236])

In [25]:
print(np.around (np.sqrt(d),2)); print(np.arange(9))

[1.16 1.76 2.22]
[0 1 2 3 4 5 6 7 8]


In [23]:
a2 = np.array([3,6,7,9+5j])
a2.dtype

dtype('complex128')

#### 2D array

In [35]:
a1 = np.array([[3,4,5,8],[7,2,8, np.NAN]])

In [36]:
a1

array([[ 3.,  4.,  5.,  8.],
       [ 7.,  2.,  8., nan]])

In [27]:
a1.shape

(2, 3)

In [29]:
a1.reshape(3,2),a1.dtype

(array([[3, 4],
        [5, 7],
        [2, 8]]),
 dtype('int32'))

In [30]:
a1.astype(float),a1.astype(str)

(array([[3., 4., 5.],
        [7., 2., 8.]]),
 array([['3', '4', '5'],
        ['7', '2', '8']], dtype='<U11'))

In [32]:
a1.astype(complex), a1.astype(bool)

(array([[3.+0.j, 4.+0.j, 5.+0.j],
        [7.+0.j, 2.+0.j, 8.+0.j]]),
 array([[ True,  True,  True],
        [ True,  True,  True]]))

In [48]:
a2 =np.array([[3,4,6],[7,9,10],[4,6,12]])
a2

array([[ 3,  4,  6],
       [ 7,  9, 10],
       [ 4,  6, 12]])

In [49]:
a2.sum(axis = 1), a2.sum(axis=0)

(array([13, 26, 22]), array([14, 19, 28]))

In [50]:
a2.multiply(axis=0)

AttributeError: 'numpy.ndarray' object has no attribute 'multiply'

In [40]:
a2 = np.array([[3,4,5],[7,2,8]])
a2

array([[3, 4, 5],
       [7, 2, 8]])

In [41]:
np.sqrt(a2)

array([[1.73205081, 2.        , 2.23606798],
       [2.64575131, 1.41421356, 2.82842712]])

In [43]:
np.mean(a2,axis=0)

array([5. , 3. , 6.5])

In [30]:
b = np.array([3,8,9.8,"98.7"])
b

array(['3', '8', '9.8', '98.7'], dtype='<U32')

In [31]:
b.astype(float)

array([ 3. ,  8. ,  9.8, 98.7])

In [51]:
a3 = np.array([[3,4,5],[7,2,8],[9,1,6]])
a3

array([[3, 4, 5],
       [7, 2, 8],
       [9, 1, 6]])

In [36]:
np.fill_diagonal(a3,0)

In [37]:
a3

array([[0, 4, 5],
       [7, 0, 8],
       [9, 1, 0]])

In [53]:
# Define two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication
C = np.matmul(A, B)

print(C)

[[19 22]
 [43 50]]


In [39]:
A.T, B.T

(array([[1, 3],
        [2, 4]]),
 array([[5, 7],
        [6, 8]]))

In [54]:
np.invert(A)

array([[-2, -3],
       [-4, -5]])

In [57]:
# Accessing the array elements
a4 = np.array([[3,4,5],[7,2,8],[9,1,6],[10,9,18]])
a4

array([[ 3,  4,  5],
       [ 7,  2,  8],
       [ 9,  1,  6],
       [10,  9, 18]])

In [61]:
a4[3][2]

18

In [70]:
a4[3]

array([10,  9, 18])

In [62]:
a4[1]

array([7, 2, 8])

In [42]:
a4[1][2], a4[2][1]

(8, 1)

In [44]:
a4[1]

array([7, 2, 8])

In [109]:
for i in a4:
    print (i[1])

4
2
1
9


In [50]:
[i[1] for i in a4]

[4, 2, 1, 9]

In [75]:
a4[:,2]

array([ 5,  8,  6, 18])

In [81]:
a4[0][0],a4[0][2]

(3, 5)

In [101]:
a4 = np.array([[3,4,5],[7,2,8],[9,1,6],[10,9,18]])
a4


array([[ 3,  4,  5],
       [ 7,  2,  8],
       [ 9,  1,  6],
       [10,  9, 18]])

In [103]:
a4[1:,2:]

array([[ 8],
       [ 6],
       [18]])

In [84]:
a3

array([[3, 4, 5],
       [7, 2, 8],
       [9, 1, 6]])

In [85]:
np.argmax(a3,axis=1),np.argmax(a3,axis=0)

(array([2, 2, 0], dtype=int64), array([2, 0, 1], dtype=int64))

In [86]:
np.amax(a3, axis =1),np.amax(a3, axis =0)

(array([5, 8, 9]), array([9, 4, 8]))

#### ELEMENT-WISE Addition, subtraction etc

In [60]:
a1= np.array([1,2,3])
a2  = np.array([3,8,9])
a1+a2

array([ 4, 10, 12])

In [4]:
a1*a2

array([ 3, 16, 27])

In [5]:
a1/a2

array([0.33333333, 0.25      , 0.33333333])

In [58]:
b1 = np.array([[1,2],[4,8]])
b2 = np.array([[3,4],[1,1]])
b1*b2

array([[3, 8],
       [4, 8]])

In [6]:
a1**a2

array([    1,   256, 19683])

In [61]:
a1,a2

(array([1, 2, 3]), array([3, 8, 9]))

In [9]:
np.logical_and(a1 , a2)

array([ True,  True,  True])

In [10]:
a1 & a2

array([1, 0, 1])

In [104]:
a1,a2

(array([[3, 4, 5],
        [7, 2, 8]]),
 array([[3, 4, 5],
        [7, 2, 8]]))